### ISSUE TITLE
Addition of IME input

### ISSUE THREAD

**Issue by moka491** [taximanli/kotobade-asobou#1]
First of all, this is an amazing take on Wordle, thank you for this!
As a learner of the language, it's a lot of fun to practice with too~

My only wish would be to be able to use my IME (Microsoft IME) on the website.
Not sure how easily accomplishable that is, I assume you need some kind of text input for that.

**Comment by deceze** [comment]
Seconded in all regards. The hunt-and-peck keyboard takes a lot of speed out of the game, which is part of what makes Wordle fun.

**Comment by sirati** [comment]
Ｉ would like to second that once more. I really do not use my mouse much for using the computer and having to is quite discouraging.

**Comment by taximanli** [comment]
Thanks for the feedback! I've developed a new version of the game which allows players to type in theirs with keyboard and it is scheduled to be release in couple of days. Please stay tuned.

**Comment by taximanli** [comment]
@moka491 @deceze @sirati Thanks for your continuous support! I've completed a new version of the game and it's now live! The game now support IME keyboard input. Players can type Japanese kana into the text box on the screen to submit their answers.

**Comment by deceze** [comment]
Nice, thank you! The new hints are also interesting. Thumbs up.
