### ISSUE TITLE
Share button doesn’t seem to work

### ISSUE THREAD

**Issue by stickykeys99** [taximanli/kotobade-asobou#10]
I know there’s a new update with Hint Mode, but the Share button doesn’t do anything.

 - Device: iPhone6s
 - OS: iOS13.3
 - Browser: Safari
 - Version: 13

**Comment by taximanli** [comment]
To further clarify this issue, when clicking the Share button, it doesn't copy results to clipboard?

**Comment by stickykeys99** [comment]
Yes, it doesn't do that for some reason.

**Comment by taximanli** [comment]
Thanks for your feedback! I have added a text box to show the daily results.

You can "Select All" and then "Copy and Paste" to share your results on social media. This should solve the Share button issue? (some browser models / settings may not allow data to be copied to clipboard)

I have also added a Tweet button. Could you see if the Tweet button works on your iPhone 6s?

**Comment by stickykeys99** [comment]
Fixed. Thanks :) However I apologize I cannot test this tweet feature as I do not have a Twitter account.
