### ISSUE TITLE
Add a dictionary add the end of the game

### ISSUE THREAD

**Issue by eddiemaero** [taximanli/kotobade-asobou#16]
**Is your feature request related to a problem? Please describe.**

When I finish the game, sometimes I don't know what the word means. 

**Describe the solution you'd like**

It would be helpful to add a dictionary to show what the word means. Of course, to avoid spoilers, this can be set as temporary.

**Describe alternatives you've considered**

If that is not possible then maybe add a link in the result to a dictionary (e.g. Jisho) so that we can click on it to check the meaning of the word.

**Additional context**

Nope, thank you for making this game!

**Comment by taximanli** [comment]
@eddiemaero Terribly sorry that I didn't add the dictionary search feature at the end of the game until now.

Players can now click on today's answer and yesterday's answer to check the meaning of the word on Jisho (please see the screenshot below, masked as two black boxes to avoid spoilers).

![image](https://user-images.githubusercontent.com/11369846/170734689-1e0699fe-26aa-429a-a709-a10911ce7788.png)
