### ISSUE TITLE
Feature Request: Add romaji input

### ISSUE THREAD

**Issue by takoyaki99** [taximanli/kotobade-asobou#18]
**Is your feature request related to a problem? Please describe.**
I'd like to have romaji input added to this game. My school laptop's Japanese typing doesn't work (I've asked the technical department if they could fix it and they didn't really help) so I'm basically stuck. Of course I can use the kana at the bottom which does help (and works fine as an input method) but I do feel that a more fluid experience could be achieved with this.

**Describe the solution you'd like**
Romaji input added--the small kana would probably be best inputted by having an x before, for example xya for ゃ. Small っ with xtsu or a double kana like the kk in 学校 (ga**kk**ou). ー with a normal dash.

**Describe alternatives you've considered**
Using the kana table provided.

**Additional context**
Thank you very much for your hard work!!

**Comment by taximanli** [comment]
Thanks for your feedback! I'm happy that you like this game and hopefully this game can assist you in learning more Japanese words. I have been busy so I only just updated the game to accept romaji and katakana input.

In additional to hiragana, now players can also directly type their guesses in romaji or katakana. Their guesses will be automatically converted to hiragana after hitting the enter button.
