### ISSUE TITLE
[Feature] archive mode

### ISSUE THREAD

**Issue by Ceynou** [taximanli/kotobade-asobou#19]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem but you're limited to only one word a day.

**Describe the solution you'd like**
It would be nice to be able to play the words from the previous days.

**Additional context**
[french wordle](https://wordle.louan.me/)

**Comment by HelenFoster** [comment]
Agreed. Perhaps also far-future games e.g. game 100000+?

**Comment by taximanli** [comment]
Hi @Ceynou @HelenFoster 

All words from the previous days are now unlocked!
Please click on the red calendar icon on the top right corner of the screen and choose a past date to play.

![image](https://github.com/taximanli/kotobade-asobou/assets/11369846/439106f0-d03e-4d9d-b7a8-489abdb42a68)

**Comment by Ceynou** [comment]
Thank you very much taximanli, very appreciated feature!
