### ISSUE TITLE
Big ゆ not recognized as 'similar' to small ゅ

### ISSUE THREAD

**Issue by JulidtheRealOne** [taximanli/kotobade-asobou#27]
I'm loving this game so far, keep up the great work!

I'm a bit confused about the hints from this puzzle. Maybe I just don't understand the rules... but shouldn't the ゆ from ゆうめい be shown with a brown circle? It's close to the correct character (big vs. small) but in the wrong position:

![Screenshot_20220409-130727~2](https://user-images.githubusercontent.com/74785319/162594676-31be8284-b285-4e8c-b02b-35b60341c680.png)

**Comment by briantist** [comment]
That should happen if they are in the same position only. Since they are different positions, that will not happen. Same as other characters like that.

**Comment by taximanli** [comment]
@JulidtheRealOne Thanks for playing the game and glad that you love the game!
Thanks @briantist for the precise explanation of the hint.
