### ISSUE TITLE
"the word for...." message obscures the actual game

### ISSUE THREAD

**Issue by jeffrey-friedl** [taximanli/kotobade-asobou#28]
**Describe the bug**
After the game has finished, the word of the day is displayed in a way that obscures the game play, making screenshots of the game play less useful for sharing with friends.

[Example](https://www.dropbox.com/s/oz79j39ocbzs0eg/ScreenShot%202022-05-01%20at%2011.19.35%20PM.png?dl=0)

It would be nice if the message could be presented in a way that did not obscure the game play.

**Comment by taximanli** [comment]
Thanks @jeffrey-friedl for the suggestion. The game now moved the pop-up message of today's word to the bottom half of the screen so it doesn't obscure the game play.
