### ISSUE TITLE
Include word みずたま　(polka dots)

### ISSUE THREAD

**Issue by jeffrey-friedl** [taximanli/kotobade-asobou#29]
The game does not allow the word みずたま.  It's a normal, common Japanese word meaning "polka dots".

**Comment by Ceynou** [comment]
It's an abbreviation, see 水玉模様

**Comment by jeffrey-friedl** [comment]
> It's an abbreviation, see 水玉模様

That's a compound word meaning "polka-dot pattern".  水玉 is a word by itself, though indeed it can be used as shorthand for 水玉模様.   In the example of 水玉飴, it's not a shorthand for 水玉模様...

**Comment by Ceynou** [comment]
you're right I went retarded and assumed kotabade-asobou's dictionary had no issue so I had to find a reason that it's not allowed, for polka dots it's an abbreviation, for drop of water it's not so it should be allowed.

**Comment by taximanli** [comment]
Sorry for the late reply. I've been busy with study and work.
Thanks @jeffrey-friedl @Ceynou for your continuous support and paying good attention to the game :)
I've double checked the word list and confirmed that the word みずたま is in the word list and is allowed in the game.
Thanks again for your comments and please don't hesitate to raise any missing words here in github and I'll add them.

![image](https://user-images.githubusercontent.com/11369846/167084508-ce6c9eeb-3fd1-4ce4-9762-5de98913d97b.png)
