### ISSUE TITLE
Katakana words are not ok

### ISSUE THREAD

**Issue by JavaPuzzler** [taximanli/kotobade-asobou#30]
Today's puzzle was impossible because it's not a real word in hiragana.

**Comment by Ceynou** [comment]
> Besides hiragana, now you can also directly type your guesses in romaji or katakana. Your guesses will be automatically converted to hiragana after hitting the enter button.

So it doesn't matter if it's a katakana word, it will be converted to hiragana, maybe you want to request one more hint:
convert a correct guess to katakana if it's a katakana word.

**Comment by eao** [comment]
Kind of agreed - I was surprised when today I put in "ぼーなす" when I couldn't think of anything else to put and it was the answer.  While you should be able to put that in for a guess, it felt slightly disappointing as an answer to the puzzle since it's just English.  Not sure if the words are manually picked.  Love the game though.

**Comment by taximanli** [comment]
Thank you @JavaPuzzler @Ceynou @eao for your comments and ideas.

To enhance gaming experience, if the answer of a certain day is a Katakana word, the panel and keys in the game will switch to Katakana mode (from normal Hiragana mode) on that day.

![image](https://user-images.githubusercontent.com/11369846/170690406-79a97a5e-72d6-41f6-91dc-a707556d601b.png)

Most of katakana words are the foreign loanwords that borrowed into the Japanese language. And these foreign loanwords actually play a every important role in daily Japanese conversation.

I hope this new change will make the game better :)

**Comment by JavaPuzzler** [comment]
That's a great solution!  Thanks so much.

どうもありがとうございました.

**Comment by eao** [comment]
Cool idea, thanks.

**Comment by eishiya** [comment]
This is a great solution, but there's a problem: clicking guesses takes you to their entry on jisho.org, but when non-katakana words are converted to katakana, the search doesn't work correctly. If possible, I think searches for incorrect guesses should always be performed in hiragana (which will also turn up katakana words) even when the correct word is in katakana, while correct katakana guesses should search in katakana.
