### ISSUE TITLE
Feature request: Archive

### ISSUE THREAD

**Issue by eao** [taximanli/kotobade-asobou#32]
Awesome game, thanks for making it.  Would be nice to be able to play past entries in an archive though.  Perhaps this is already possible with time/date spoofing, I didn't test it, but would be nice to have it as an inbuilt feature regardless.

**Comment by taximanli** [comment]
Hi @eao , all past entries are now unlocked!
Please click on the red calendar icon on the top right corner of the screen and choose a past date to play.

![image](https://github.com/taximanli/kotobade-asobou/assets/11369846/439106f0-d03e-4d9d-b7a8-489abdb42a68)
