### ISSUE TITLE
Input bar location - optional?

### ISSUE THREAD

**Issue by briantist** [taximanli/kotobade-asobou#33]
It looks like the input bar was placed below the keyboard in f81612b3be14a10c05090db42ca1eebc4bba25fc but it doesn't seem linked to a request or problem.

On the screen I usually play on, this now puts the input bar below the fold, and I have to scroll down and back up to look at the guess or the input. I could make the text smaller but then it's hard to read.

I could see how some people might like it better at the bottom though, might be nice to make the location optional?

**Comment by kooolm** [comment]
Same

**Comment by taximanli** [comment]
@briantist @kooolm 

(In Twitter, some players requested the text box to be positioned at the bottom)

But yes, providing an option setting for the position of text box is a great idea! Thanks for the suggestion.

I have just updated the game. Players can now select the positions of text box and kana chart in Settings.

![Screenshot_20220526-024423_Chrome.jpg](https://user-images.githubusercontent.com/11369846/170319855-a120669d-a4e7-40ef-bb3f-b7637e33f2bc.jpg)

**Comment by briantist** [comment]
@taximanli thanks so much for that!
