### ISSUE TITLE
Wiping browser history wiped my statistics

### ISSUE THREAD

**Issue by Sodomatron** [taximanli/kotobade-asobou#35]
I just wiped my cache and browser history, and I noticed that all of my stats are gone. Could there be another way to store our progress like accounts ?

**Comment by taximanli** [comment]
@Sodomatron , sorry to hear that all of your stats are gone. Currently the game doesn't require players to have user accounts to play so player's stats are stored at the local storage in browser (similar to cookies), therefore the stats are gone after clearing your browser cache.

However there's a way to add back your stats in your browser. Do you use Twitter? Message me on Twitter so I can show you the way. My Twitter ID is @taximanli
