### ISSUE TITLE
Hint mode not working properly ?

### ISSUE THREAD

**Issue by mmagain99** [taximanli/kotobade-asobou#36]
Disclaimer : It might not be a bug but just a lack of understanding of how the hints work.

I thought every single guess was supposed to display arrows if a correct letter was in the same row/column. If I understand correctly, then に, し and き should have horizontal arrows on them since ち is in the word (see belowscreenshot). Same thing goes for the column involving ち, some vertical arrows are missing. (Same for の etc.)

![image](https://user-images.githubusercontent.com/54215546/172076483-f87d53f9-f8ae-470e-83d4-e6a70721a1a4.png)

**Comment by Sodomatron** [comment]
> 

I think the ぎ hint is normal because they are considered to be the same row. See the explanation on the website  : "Each ROW contains kana that have the matching vowel, e.g. both UPPER row う く す つ ぬ ふ む ゆ る and LOWER row ぅ ぐ ず づ っ ぶ ぷ ゅ ゔ are treated as the SAME row with the matching vowel U."

**Comment by ntfshard** [comment]
I see, but life is too short to read instructions)) It could be more intuitive if it will literally in one row. Or treated like different rows.

> However, も and こ should be hinting towards の, which they aren't.

+た

**Comment by HelenFoster** [comment]
Took me a while to understand this one too, but you only get arrows if the hinted character is in the same position in the word as the character you guessed.

**Comment by mmagain99** [comment]
> 

It does make sense indeed now. Thanks !
