### ISSUE TITLE
Minor bug on hints

### ISSUE THREAD

**Issue by sgaropazio** [taximanli/kotobade-asobou#37]
In hint mode when you send a word containing two times the same character, one in the right place and the other where is supposed to be a character in the same row, the hint on the word correctly shows horizontal arrows, while the hint on the keyboard shows the character in yellow (see screenshot).

So the precedence of the hints seems to be wrong on the keyboard. 

see screenshot, on today's word:
<details>
  <summary>Spoiler for Game #153 on June 25, 2022</summary>
  
![](https://i.ibb.co/wsnq6xF/ops.png)

</details>

**Comment by taximanli** [comment]
@sgaropazio This minor bug on hints has been resolved thanks to the Hint priority fix contributed by @achamberlain999
