### ISSUE TITLE
Google Drive sync

### ISSUE THREAD

**Issue by denrix0** [taximanli/kotobade-asobou#38]
On occasion I've moved browsers and it would be nice to keep my progress synced in case I lost my browser storage/cookies or wherever the progress data is stored.

It would be convenient, say for not missing a day when I'm unable to access my laptop, and helpful in case of accidentally deleting progress to sync our google drive accounts to make sure progress is preserved,

Perhaps exporting and importing data would also be an alternative option?

**Comment by denrix0** [comment]
Yes, that also works! Thank you!

**Comment by CodedbyRed** [comment]
OMG thank you so much, you can also close my issue re: device transfer
