### ISSUE TITLE
 ​​

### ISSUE THREAD

**Issue by benlanier** [taximanli/kotobade-asobou#4]

**Comment by taximanli** [comment]
Thank you for spotting this issue. It has now been fixed.

Kotobade Asobou 言葉で遊ぼう 7 5/12
https://taximanli.github.io/kotobade-asobou/
⬛🟧⬛⬛
⬛🟦⬛🟦
🟧🟧⬛🟧
🟧🟧⬛🟧
🟧🟧🟧🟧
