### ISSUE TITLE
How to move stats to another phone?

### ISSUE THREAD

**Issue by CodedbyRed** [taximanli/kotobade-asobou#42]
Hi! I have a streak of 532 and I'm switching phones (still have my old) both android. Does anyone know of a way outside of google sync (I don't know if that would work but I can't use that because I have legit 3000 tabs open on old phone, I'm not messing with that haha) to bring my stats over to my new phone?

I saw on one of the closed issues that there was a way and to message on twitter but I'm not on twitter. 

Thank you very much

**Comment by taximanli** [comment]
Hi @CodedbyRed , you can now transfer your game stats to your new phone, by coping the migration code from your old phone and paste it to the new phone.

![image](https://github.com/taximanli/kotobade-asobou/assets/11369846/b420d668-5947-4ae9-8c43-a08066d175b8)

![image](https://github.com/taximanli/kotobade-asobou/assets/11369846/44d282af-c0c3-4cb4-a5d2-3409432f4178)

**Comment by CodedbyRed** [comment]
THANK YOUUUU
