### ISSUE TITLE
Have a page reload tee up the current day's game

### ISSUE THREAD

**Issue by jeffrey-friedl** [taximanli/kotobade-asobou#46]
I'm not sure whether this is a bug report or a feature request, but since you added the ability to play previous-day's games, I can't play the current-day's game without going to the calendar to select the day, which I don't do until I'm done playing and I realize that I just played yesterday's game again.  It'd be nice if a page reload always opened up to the current day's game, as it did in the year(s) prior to adding the calendar feature.   Thanks.

**Comment by taximanli** [comment]
Hi @jeffrey-friedl , thanks for reporting the bug. I have quickly put in a fix to the game and aim to address the issue of a page reload not opening up to the current day's game.

Please refresh your browser / mobile screen and play today's game. And when you open the game tomorrow, it should load tomorrow's game without going to the calendar to select the day.

Please let me know if that works for you tomorrow. If that doesn't work as expected, please let me know so I can continue bug fixing.

**Comment by jeffrey-friedl** [comment]
It works well now, thanks!!
