### ISSUE TITLE
The word 「おくやみ」 【お悔やみ】 is not in the game's dictionary.

### ISSUE THREAD

**Issue by jeffrey-friedl** [taximanli/kotobade-asobou#48]
A minor thing, but I'd think that お悔やみ should be in the dictionary. I wanted to use it as my starting word today, since my dad passed away yesterday.

**Comment by taximanli** [comment]
Hi @jeffrey-friedl , sorry to hear your loss. おくやみ is now added as a valid guess word.
心からお悔やみ申し上げます。

**Comment by jeffrey-friedl** [comment]
Thanks so much!
