### ISSUE TITLE
Ending the previous day's game after midnight appears to lock you out of the subsequent day's

### ISSUE THREAD

**Issue by not-nocturnal** [taximanli/kotobade-asobou#6]
I started #31 at 9pm or so, then forgot about it and finished just past midnight, and now refreshing just shows me my completed game (#31) and tells me I need to wait 23 more hours.

**Comment by taximanli** [comment]
Thanks for your bug report! I've developed a new version of the game and it is scheduled to be release in couple of days. I'll test it to see if the same bug persists.

**Comment by briantist** [comment]
I also had this bug happen maybe 2 weeks ago, but perhaps it's already fixed in the new release. I had to open the developer tools and mess with some of the stored JS values to fix it previously.

**Comment by taximanli** [comment]
After the new release, I don't see the same issue occurring ever again. This issue is now considered fixed. :)

**Comment by briantist** [comment]
thanks for the great game and the improvements @taximanli !
