### ISSUE TITLE
Game crashes when input box has more than 4 characters

### ISSUE THREAD

**Issue by menma1234** [taximanli/kotobade-asobou#7]
**Describe the bug**
In the kana input box, when it contains more than 4 characters, the game crashes. This can be pretty annoying if the word you want to guess ends with ち or つ and you type them as "chi" or "tsu" in a romaji input method, since it'll get rendered as "かどまts" for example in the input box temporarily.

**To Reproduce**
1. Enter ああああ in the input box (or any 4 characters).
2. Enter any other character.
3. Game crashes and gives a blank screen.

**Expected behavior**
Game handles it gracefully.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox (also tested in Chrome)
 - Version: FF 97.0.1 / Chrome 98

**Comment by briantist** [comment]
I came here to open this same issue. I ran into it trying to type まいにち because as soon as I hit the `h` it triggered the crash (for an example when this could happen with valid input).

**Comment by taximanli** [comment]
@menma1234 @briantist Thank you for report this critical bug! Very much appreciated. I've pushed the fix for the input box issue. Please refresh the game and let me know if it now works well for you.

**Comment by briantist** [comment]
Thanks very much, I will have to let you know tomorrow since I completed the game today 😁

**Comment by menma1234** [comment]
Yep, looks fixed, thanks!
