### ISSUE TITLE
Arrow hint not shown correctly

### ISSUE THREAD

**Issue by TonalidadeHidrica** [taximanli/kotobade-asobou#9]
**Describe the bug**
The arrow mark ⇄ did not show up correctly

**To Reproduce**
It happened for the following case:

<details><summary>Spoiler for Day 37</summary>
<img width="242" alt="image" src="https://user-images.githubusercontent.com/47710717/156010629-105eae36-998c-49e1-91a5-733fedaf97c1.png">
「た」has same vowel as 「だ」, so I think the arrow hint ⇄ should be displayed.
</summary>

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 98.0.4758.109

**Comment by Parmacenda** [comment]
Can confirm something similar happened to me too, both with the horizontal and vertical arrows.

- OS: MacOS Big Sur
- Browser: Chrome Version 96.0.4664.93

<details>
<summary>Spoiler for day 37</summary>

![Game 37 - Weird Arrow Hints](https://user-images.githubusercontent.com/58598328/156080810-8ebf34f0-0201-4fe1-a263-4be669a6fd1d.png)
If I understand how the arrow hints should display, then たべもの should have horizontal arrows on both た and べ, and vertical arrows on の. Also, both に and で later should have vertical arrows.
Unless there is some system to avoid filling most kana with arrows for those of us that use a lot of guesses, it seems that most of the time the arrows are not appearing.
</details>

**Comment by taximanli** [comment]
The game manual I have written may not have explained the rules for arrows clearly. (the game manual can be opened by clicking the top left Info icon on the screen).

In hint mode, the game checks each kana in your guess against the kana in the correct answer in the same spot only, but not checking against kana in a different spot,
i.e.
1st kana in your guess is checked against 1st kana in the correct answer, but not against 2nd, 3rd, 4th kana in the correct answer...
2nd kana in your guess is checked against 2nd kana in the correct answer, but not against 1st, 3rd, 4th kana in the correct 
3rd kana in your guess is checked against 3rd kana in the correct answer, but not against 1st, 2nd, 4th kana in the correct 
4th kana in your guess is checked against 4th kana in the correct answer, but not against 1st, 2nd, 3rd kana in the correct 

<details>
<summary>I'll use the above examples to explain it more clearly.</summary>
In @TonalidadeHidrica 's example, 
たいこう VS ねんだい: た TA and ね NE do not have same consonants / vowels, so no arrows display

In @Parmacenda 's example, 
でかける VS ねんだい: で DE and ね NE have the same vowel, so no horizontal arrows display
</details>

I did come short in explaining the rules on the game manual. Could you guys so kindly help proof-read the game instructions and suggest how exactly I should rewrite any part?

![Screenshot_20220301-184619_Chrome](https://user-images.githubusercontent.com/11369846/156133694-d1c99e75-5816-43a1-8367-2277026f4a02.jpg)

![Screenshot_20220301-184706_Chrome](https://user-images.githubusercontent.com/11369846/156133715-f931300b-39f9-40ff-b84c-926573bbf5e6.jpg)

![Screenshot_20220301-192911_Chrome](https://user-images.githubusercontent.com/11369846/156133732-d2325a3d-4816-42d6-8101-f1ba4927dff4.jpg)

![Screenshot_20220301-192953_Chrome](https://user-images.githubusercontent.com/11369846/156133749-137cb657-7d1d-4e7d-92fc-44d65a305b04.jpg)

**Comment by TonalidadeHidrica** [comment]
Ah, I see.  I missed the fact that the position should match, which is clearly written in the rules.  Sorry for the wrong issue!
